#!/usr/bin/env bash
# =============================================================================
# webhook-tls.sh — Set up HTTPS for the webhook listener
# =============================================================================
# Two modes depending on NGINX_MODE in config.env:
#
#   behind-nginx → writes an nginx snippet to NGINX_CONF_DIR for your existing
#                  nginx to terminate TLS (you provide cert via certbot).
#
#   standalone   → runs a small Caddy container on a non-standard port (8443)
#                  with self-signed TLS. Bearer token is the real auth.
#
# Webhook URL after this:
#   behind-nginx:  https://deploy.<BASE_DOMAIN>/deploy        (your nginx)
#   standalone:    https://deploy.<BASE_DOMAIN>:8443/deploy   (Caddy)
#
# Usage:  sudo ./scripts/webhook-tls.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="${CONFIG_FILE:-$PROJECT_DIR/config.env}"
[ -f "$CONFIG_FILE" ] && source "$CONFIG_FILE"

BASE_DOMAIN="${BASE_DOMAIN:?BASE_DOMAIN not set in config.env}"
ACME_EMAIL="${ACME_EMAIL:-admin@${BASE_DOMAIN}}"
NGINX_MODE="${NGINX_MODE:-standalone}"
NGINX_CONF_DIR="${NGINX_CONF_DIR:-/etc/nginx/dokku-tenants}"
WEBHOOK_HOST="deploy.${BASE_DOMAIN}"
WEBHOOK_PORT="${WEBHOOK_PORT:-9999}"

echo "Webhook host: ${WEBHOOK_HOST}"
echo "Mode:         ${NGINX_MODE}"
echo ""

if [ "$NGINX_MODE" = "behind-nginx" ]; then
    SNIPPET="${NGINX_CONF_DIR}/00-webhook.conf"
    mkdir -p "$NGINX_CONF_DIR"

    cat > "$SNIPPET" <<NGINX
# Auto-generated by webhook-tls.sh — webhook reverse proxy
server {
    listen 443 ssl http2;
    server_name ${WEBHOOK_HOST};

    ssl_certificate     /etc/letsencrypt/live/${WEBHOOK_HOST}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${WEBHOOK_HOST}/privkey.pem;

    location /deploy {
        proxy_pass http://127.0.0.1:${WEBHOOK_PORT}/deploy;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$remote_addr;
        proxy_read_timeout 30s;
    }
}
NGINX

    echo "✓ Nginx snippet written: ${SNIPPET}"
    echo ""
    echo "Next steps:"
    echo "  1. Add DNS:  ${WEBHOOK_HOST} → this server's IP"
    echo "  2. Get cert: sudo certbot --nginx -d ${WEBHOOK_HOST}"
    echo "  3. Reload:   sudo nginx -t && sudo systemctl reload nginx"
    echo "  4. Update GitHub Secrets:"
    echo "       WEBHOOK_URL_DEV  = https://${WEBHOOK_HOST}/deploy"
    echo "       WEBHOOK_URL_PROD = https://${WEBHOOK_HOST}/deploy"
    exit 0
fi

# ---- Standalone mode: Dokku owns 80/443, run Caddy on 8443 ----
CADDY_DIR=/opt/webhook-caddy
mkdir -p "$CADDY_DIR/data" "$CADDY_DIR/config"

cat > "$CADDY_DIR/Caddyfile" <<EOF
{
    email ${ACME_EMAIL}
    auto_https disable_redirects
}

${WEBHOOK_HOST}:8443 {
    tls internal
    reverse_proxy host.docker.internal:${WEBHOOK_PORT}
}
EOF

docker rm -f webhook-tls 2>/dev/null || true
docker run -d \
    --name webhook-tls \
    --restart always \
    --add-host=host.docker.internal:host-gateway \
    -p 8443:8443 \
    -v "$CADDY_DIR/Caddyfile:/etc/caddy/Caddyfile:ro" \
    -v "$CADDY_DIR/data:/data" \
    -v "$CADDY_DIR/config:/config" \
    caddy:2-alpine

if command -v firewall-cmd &>/dev/null; then
    firewall-cmd --add-port=8443/tcp --permanent 2>/dev/null && firewall-cmd --reload 2>/dev/null || true
elif command -v ufw &>/dev/null; then
    ufw allow 8443/tcp 2>/dev/null || true
fi

echo "✓ Caddy webhook proxy running on :8443 with self-signed TLS."
echo ""
echo "Webhook URL:  https://${WEBHOOK_HOST}:8443/deploy"
echo ""
echo "NOTE: 'tls internal' uses self-signed certs. The bearer token is the real auth."
echo "      The CI workflow will need 'curl -k' to skip cert verification, OR use"
echo "      NGINX_MODE=behind-nginx for a real Let's Encrypt cert."
